Feature/grupos
TCC2020/bbooks-backend pull request #93
Opened 2021-02-07 22:51 UTC by Nessaoana

2021-02-07 23:27 UTC, feloureiro requested changes

2021-02-07 23:27 UTC, feloureiro commented on feed-api/src/main/java/br/edu/ifsp/spo/bulls/feed/api/controller/GroupMemberController.java
> +    public List<GroupMembers> getGroupByUser(@PathVariable UUID id) {
Acho que aqui esse objeto embbaded atrapalha no front, talvez uma lista de grupo seja melhor(confirmar com o andré)

2021-02-07 23:27 UTC, feloureiro commented on feed-api/src/main/java/br/edu/ifsp/spo/bulls/feed/api/service/GroupService.java
> +    public GroupTO save(GroupTO groupTO) {
Aqui seria interessante colocar o feign para chamar a api de users para veriicar se o usuário realmente existe (aquela inteligência no nível de aplicação que o Daniel falou)
Tem que ver se tá criando o relacionamento no banco, se não tiver, é interessante colocar isso.

2021-02-07 23:27 UTC, feloureiro commented on feed-api/src/main/java/br/edu/ifsp/spo/bulls/feed/api/bean/PostBeanUtil.java
>              System.out.println(postTO);
Remover sout

2021-02-07 23:39 UTC, Nessaoana commented on feed-api/src/main/java/br/edu/ifsp/spo/bulls/feed/api/service/GroupService.java
> +    public GroupTO save(GroupTO groupTO) {
Não cria o relacionamento com o mapeamento.. Foi isso que perguntei a ele. Havia entendido que não precisava

2021-02-08 23:54 UTC, feloureiro commented on feed-api/src/main/java/br/edu/ifsp/spo/bulls/feed/api/service/GroupService.java
> +    public GroupTO save(GroupTO groupTO) {
Mas não é para criar o relacionamento é para ver se o usuário existe para não salvar dado incoerente

2021-02-09 01:06 UTC, Nessaoana commented on feed-api/src/main/java/br/edu/ifsp/spo/bulls/feed/api/service/GroupService.java
> +    public GroupTO save(GroupTO groupTO) {
Feito

2021-02-11 01:50 UTC, nfandre approved these changes

2021-02-11 02:13 UTC, feloureiro approved these changes

2021-02-11 02:13 UTC, merged